name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: test_app          # thư mục chứa buildozer.spec
          buildozer_version: stable
        env:
          USER: root
          PIP_BREAK_SYSTEM_PACKAGES: "1"

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-packages
          path: test_app/bin/*.apk   # upload tất cả file APK được tạo ra
